import type { Metadata } from "next";
import localFont from "next/font/local";
import { Anek_Devanagari} from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar/navbar";



const anek = Anek_Devanagari ({ subsets: ["latin"] , weight:"400" });

export const metadata: Metadata = {
  title: "Valorant info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anek.className} antialiased`}
      >  
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
